In [73]:
import pandas as pd

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

from bs4 import BeautifulSoup

In [29]:
options = Options()
options.add_argument("--user-data-dir=/Users/renato/Library/Application Support/Google/Chrome/")
options.add_argument(r'--profile-directory=Profile 2') #e.g. Profile 3
driver = webdriver.Chrome(executable_path=r'/Users/renato/Downloads/chromedriver', chrome_options=options)
driver.get("https://br108.tribalwars.com.br/page/play/br108")
driver.get("https://br108.tribalwars.com.br/game.php?screen=ally&mode=members_troops")

<ipython-input-29-842be0b07982>:4: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'/Users/renato/Downloads/chromedriver', chrome_options=options)

In [67]:
url_trops_players = "https://br108.tribalwars.com.br/game.php?screen=ally&mode=members_troops&player_id={player_id}"
html_members_selection = driver.page_source 
soup = BeautifulSoup(html_members_selection, 'html.parser')
players = [[opt['value'], opt.text] for opt in soup.select('select[name=player_id] > option[value]')]

In [69]:
result_list = []
for player_id, name in players:
    url_trop_player = url_trops_players.format(player_id=player_id)
    driver.get(url_trop_player)
    html_player_trops = driver.page_source 
    soup = BeautifulSoup(html_player_trops, 'html.parser')
    table = soup.find('table', {"class": "vis w100"})
    aldeias = table.find_all('tr')[1:]
    total = []
    for aldeia in aldeias:
        result_aldeia = [tr.text.strip() for tr in aldeia.find_all('td')]
        result_aldeia.insert(0, name)
        total.append(result_aldeia)

    result_list += total

In [40]:
soup.select('select[name=player_id] > option')

[<option hidden="">Selecionar membro</option>,
 <option value="918902501">
                 *TROIA*             </option>,
 <option value="919439534">
                 Ablonblackangel             </option>,
 <option value="919603606">
                 Apolo100             </option>,
 <option value="919620388">
                 Caio limaa             </option>,
 <option value="7524409">
                 Camaro2011             </option>,
 <option value="919627547">
                 Cefiz             </option>,
 <option value="919623482">
                 Daniel Carvalho             </option>,
 <option value="919627550">
                 Dedegas             </option>,
 <option value="919643184">
                 dingolbel             </option>,
 <option value="7765255">
                 diziin             </option>,
 <option value="919630040">
                 Dominic2611             </option>,
 <option value="919629794">
                 E.Diniz             </option>,
 <option value="919492700">
                 felipepb             </option>,
 <option value="919641647">
                 FloripaCampeche             </option>,
 <option value="919640916">
                 Galebss             </option>,
 <option value="2193927">
                 gunavale             </option>,
 <option value="919049507">
                 IMPERADOR KAMIMURA             </option>,
 <option value="7962906">
                 INDIO SEPÉ             </option>,
 <option value="919639575">
                 indiourbano             </option>,
 <option value="919604595">
                 italo-binno             </option>,
 <option value="6189796">
                 ivan mario             </option>,
 <option value="919613519">
                 kaverao             </option>,
 <option value="6932371">
                 kcond             </option>,
 <option value="919271188">
                 kelvin             </option>,
 <option value="919555411">
                 kerpoo             </option>,
 <option value="5985058">
                 Kevyn 398             </option>,
 <option value="8139727">
                 KiiroSenkou             </option>,
 <option value="919629037">
                 Kiuby             </option>,
 <option value="6270184">
                 LEANDRO P             </option>,
 <option value="919641406">
                 leomondega             </option>,
 <option value="919611178">
                 Li Qiye             </option>,
 <option value="919473052">
                 Libertário             </option>,
 <option value="919516208">
                 Lord Matheus             </option>,
 <option value="919615975">
                 lorde dos anjos             </option>,
 <option value="918992515">
                 Lucas.kaka             </option>,
 <option value="919620364">
                 Mauricio charao             </option>,
 <option value="1950517">
                 Mayckonndr             </option>,
 <option value="919641748">
                 mike careca             </option>,
 <option value="919629377">
                 Newark             </option>,
 <option value="919627616">
                 Niloo             </option>,
 <option value="6735816">
                 Off.             </option>,
 <option value="919597214">
                 OZOB             </option>,
 <option value="919608071">
                 pbxl             </option>,
 <option value="918935525">
                 Peeckz             </option>,
 <option value="919138243">
                 piedade             </option>,
 <option value="919252154">
                 predador258             </option>,
 <option value="919631431">
                 predilect10             </option>,
 <option value="7944926">
                 renatocesarlira             </option>,
 <option value="2215063">
                 Rokcclane             </option>,
 <option value="919354657">
                 Sibus             </option>,
 <option value="919064878">
                 STORM 1             </option>,
 <option value="919573610">
                 str4tegist             </option>,
 <option value="7909782">
                 Stvitinho             </option>,
 <option value="7574915">
                 taffarel12             </option>,
 <option value="919380655">
                 tunico petry 65             </option>,
 <option value="918955716">
                 vitorcabeoso             </option>,
 <option value="919424481">
                 vrauz             </option>,
 <option value="8196536">
                 willianzachow             </option>,
 <option value="7571838">
                 yuji da matta             </option>,
 <option value="919122613">
                 zTioSam             </option>]

In [75]:
df = pd.DataFrame(result_list)

In [76]:
df.columns = ['Player', 'Aldeia', 'Lança', 'Espada', 'Machado', 'Explorador', 'Cavalaria Leve', 'Cavalaria Pesada', 'Ariete', 'Cataputa', 'Paladino', 'Nobre', 'Milicia', 'Comandos ativos', 'Ataques a chegar']

In [79]:
df['Player'] = df['Player'].apply(lambda x: x.strip())

In [80]:
df

,Player,Aldeia,Lança,Espada,Machado,Explorador,Cavalaria Leve,Cavalaria Pesada,Ariete,Cataputa,Paladino,Nobre,Milicia,Comandos ativos,Ataques a chegar
0,*TROIA*,129 a.C. Ásia (Asia (546|456) K45,0,0,0,0,0,0,0,0,0,0,0,0,0
1,*TROIA*,Aldeia de Sacyqueira14 (546|457) K45,2045,2387,0,213,0,0,0,0,0,0,0,1,0
2,*TROIA*,Farmville (550|449) K45,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Ablonblackangel,Illyrium (541|434) K45,68,90,6017,170,1992,21,400,84,1,1,0,199,0
4,Ablonblackangel,Maine CooN (543|434) K45,4160,3891,0,601,0,36,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,zTioSam,Bonde do Tanza ... (534|429) K45,?,?,?,?,?,?,?,?,?,?,?,?,0
296,zTioSam,Farm (548|414) K45,?,?,?,?,?,?,?,?,?,?,?,?,0
297,zTioSam,Nobre (554|420) K45,?,?,?,?,?,?,?,?,?,?,?,?,0
298,zTioSam,Nobre (567|425) K45,?,?,?,?,?,?,?,?,?,?,?,?,0
299,zTioSam,Nobre (552|421) K45,?,?,?,?,?,?,?,?,?,?,?,?,0

In [1]:
text_to_forum = ''
current_player = ''
for index, row in df.iterrows():
    if current_player != row['Player']:
        current_player = row['Player']
        text_to_forum = f"""[/table]\n\n\n
Player: [player]{row['Player']}[/player]


[table]
[**]Aldeia[building]main[/building][||][unit]spear[/unit][||][unit]sword[/unit][||][unit]axe[/unit][||][unit]spy[/unit][||][unit]light[/unit][||][unit]heavy[/unit][||][unit]ram[/unit][||][unit]catapult[/unit][||][unit]knight[/unit][||][unit]snob[/unit][||][unit]militia[/unit][||]Comandos Ativos[||]Ataques a chegar[/**]
        """
    text_to_forum += f"[*][coord]{row['Aldeia']}[/coord] [|] {row['Lança']} [|] {row['Espada']} [|] {row['Machado']} [|] {row['Explorador']} [|] {row['Cavalaria Leve']} [|] {row['Cavalaria Pesada']} [|] {row['Ariete']} [|] {row['Cataputa']} [|] {row['Paladino']} [|] {row['Nobre']} [|] {row['Milicia']} [|] {row['Comandos ativos']} [|] {row['Ataques a chega']} "
text_to_forum = '[/table]'
print(text_to_forum)

SyntaxError: f-string: unmatched '[' (<ipython-input-1-133dda007a68>, line 13)

In [100]:
df.to_excel('tropas_tribo.xlsx')

In [99]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.7-py2.py3-none-any.whl (243 kB)
     |████████████████████████████████| 243 kB 894 kB/s eta 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.7
Note: you may need to restart the kernel to use updated packages.